services:
  - type: web
    name: dash-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PORT
        value: 10000  # you can set 8050 or let Render choose

  - type: web
    name: flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python erp_salesdatagen.py
    plan: free
    envVars:
      - key: PORT
        value: 10001  
